# Generated by Django 5.2.7 on 2025-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_is_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("password_reset", "Сброс пароля"),
                            ("email_confirm", "Подтверждение почты"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
            },
        ),
        migrations.AlterModelOptions(
            name="managerprofile",
            options={"verbose_name": "Менеджер", "verbose_name_plural": "Менеджеры"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="lectorprofile",
            name="specialization",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="managerprofile",
            name="access_level",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="managerprofile",
            name="department",
            field=models.CharField(max_length=100),
        ),
    ]
