# Generated by Django 5.2.7 on 2025-10-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_verificationcode_alter_managerprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("password_reset", "Сброс пароля"),
                    ("email_confirm", "Подтверждение почты"),
                    ("change_password", "Смена пароля"),
                ],
                max_length=20,
            ),
        ),
    ]
