# Generated by Django 5.2.7 on 2025-11-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_deactivate_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
