# Generated by Django 5.2.7 on 2025-10-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Детали получателей"
            ),
        ),
    ]
