# Generated by Django 5.2.7 on 2025-11-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_time", models.DateTimeField(verbose_name="Время отправки")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Отправлено"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_times",
                        to="mailing.mailing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Время отправки",
                "verbose_name_plural": "Времена отправки",
                "ordering": ["send_time"],
            },
        ),
    ]
